trigger:
  branches:
    include:
    - main
    - working

pr:
  branches:
    include:
    - main
    - working

name: $(Date:yyyyMMdd).$(Rev:r)

pool:
  vmImage: ubuntu-latest

variables:
  commitHash: $(Build.SourceVersion)
  
stages:
# Build Stage
 - stage: build
   displayName: "build stage"
   jobs:
     - job: build
       displayName: build a job
       pool:
         vmImage: ubuntu-latest
       steps:
       # build docker image and push to Azure Container Registry ACR

        - task: Bash@3
          displayName: "Set commitAndBuildNumber"
          inputs:
            targetType: 'inline'
            script: |
                  shortCommit=$(echo $(Build.SourceVersion) | cut -c1-8)
                  combined="${shortCommit}_$(Build.BuildNumber)"
                  echo "##vso[task.setvariable variable=commitAndBuildNumber]$combined"
        - task: Docker@2
          inputs:
            containerRegistry: 'edutech-acr'
            ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
              repository: $(imageName)
            ${{ if eq(variables['Build.SourceBranchName'], 'working') }}:
              repository: $(imageTestName)
            command: 'buildAndPush'
            Dockerfile: $(Dockerfile)
            buildContext: $(buildContext)
            tags: |
              $(commitAndBuildNumber)