<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BackGroundService\EmailNotificationBackgroundService.cs" />
    <Compile Remove="Interfaces\IApplicationUserService.cs" />
    <Compile Remove="Interfaces\ICandidateService.cs" />
    <Compile Remove="Interfaces\ICourseService.cs" />
    <Compile Remove="Interfaces\IDashboardService.cs" />
    <Compile Remove="Interfaces\IDepartmentService.cs" />
    <Compile Remove="Interfaces\IEnforcementActionService.cs" />
    <Compile Remove="Interfaces\IEnforcementModeService.cs" />
    <Compile Remove="Interfaces\IExamScheduleService.cs" />
    <Compile Remove="Interfaces\IExamService.cs" />
    <Compile Remove="Interfaces\IFacultyService.cs" />
    <Compile Remove="Interfaces\IInstitutionService.cs" />
    <Compile Remove="Interfaces\IInstitutionTypeService.cs" />
    <Compile Remove="Interfaces\ILevelService.cs" />
    <Compile Remove="Interfaces\IProctorMeTrackerService.cs" />
    <Compile Remove="Interfaces\IProctorService.cs" />
    <Compile Remove="Interfaces\IProgramService.cs" />
    <Compile Remove="Interfaces\IQuestionBankService.cs" />
    <Compile Remove="Interfaces\ISemesterService.cs" />
    <Compile Remove="Interfaces\ISessionService.cs" />
    <Compile Remove="Interfaces\ITokenService.cs" />
    <Compile Remove="Interfaces\ITutorsService.cs" />
    <Compile Remove="Services\ApplicationUserService.cs" />
    <Compile Remove="Services\CandidateService.cs" />
    <Compile Remove="Services\CourseService.cs" />
    <Compile Remove="Services\DashboardService.cs" />
    <Compile Remove="Services\DepartmentService.cs" />
    <Compile Remove="Services\EnforcementActionService.cs" />
    <Compile Remove="Services\EnforcementModeService.cs" />
    <Compile Remove="Services\ExamScheduleService.cs" />
    <Compile Remove="Services\ExamService.cs" />
    <Compile Remove="Services\FacultyService.cs" />
    <Compile Remove="Services\InstitutionService.cs" />
    <Compile Remove="Services\InstitutionTypeService.cs" />
    <Compile Remove="Services\LevelService.cs" />
    <Compile Remove="Services\ProctorMeTrackerService.cs" />
    <Compile Remove="Services\ProctorService.cs" />
    <Compile Remove="Services\ProgramService.cs" />
    <Compile Remove="Services\QuestionBankService.cs" />
    <Compile Remove="Services\SemesterService.cs" />
    <Compile Remove="Services\SessionService.cs" />
    <Compile Remove="Services\TokenService.cs" />
    <Compile Remove="Services\TutorsService.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\qguardbackend.Data\qguardbackend.Data.csproj" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc" Version="6.4.1" />
		<PackageReference Include="Azure.Storage.Blobs" Version="12.19.1" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="6.4.0" />
		<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.7" />
		<PackageReference Include="AWSSDK.S3" Version="3.7.107.2" />
		<PackageReference Include="Azure.Storage.Queues" Version="12.22.0" />
		<PackageReference Include="BCrypt.Net-Next.StrongName" Version="4.0.3" />

		<PackageReference Include="ClosedXML" Version="0.104.1" />
		<PackageReference Include="Bricelam.EntityFrameworkCore.Pluralizer" Version="1.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="FluentEmail.Core" Version="3.0.2" />
		<PackageReference Include="Mailjet.Api" Version="3.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.14" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.2" />
		<PackageReference Include="Polybioz.HtmlRenderer.PdfSharp.Core" Version="1.1.0" />
		<PackageReference Include="FluentEmail.SendGrid" Version="3.0.2" />
		<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="FirebaseAuthentication.net" Version="4.1.0" />

		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
		<PackageReference Include="FirebaseAdmin" Version="3.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.14" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.14">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.14">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="FluentValidation" Version="11.5.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Serilog" Version="4.2.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />

		<PackageReference Include="Serilog.Enrichers.Environment" Version="2.2.0" />
		<PackageReference Include="Serilog.Enrichers.Process" Version="2.0.2" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="8.0.0" />
		<PackageReference Include="Serilog.Sinks.Async" Version="1.5.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="5.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="Serilog.Sinks.MSSqlServer" Version="5.6.1" />
		<PackageReference Include="Serilog.Sinks.Seq" Version="5.1.1" />


		<PackageReference Include="NWebsec.AspNetCore.Middleware" Version="3.0.0" />
		<PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="8.0.14" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.14" />
		<PackageReference Include="RestSharp" Version="112.1.0" />
	</ItemGroup>

</Project>
